# Estágio 1: Build
FROM node:20-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build -- --configuration=production

# Estágio 2: Servidor Web (Nginx)
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos gerados pelo Angular 17+
COPY --from=builder /app/dist/front-angular/browser /usr/share/nginx/html

# Copia a configuração do Nginx com Proxy para a API
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
